--!strict
-- Inventory items, ammo, consumables, key items.
-- Inventory items: weapons, ammo, consumables, key items, weapon mods.
-- Size is in grid cells (w*h) for the Tetris-style inventory grid.

export type ItemDef = {
    id: string,
    name: string,
    category: string,           -- "Weapon", "Ammo", "Consumable", "Tool", "Key", "Aug"
    width: number,
    height: number,
    stackable: boolean,
    stackMax: number,
    description: string,
    useEffect: string?,         -- handled by InventoryService
    valueAmount: number?,       -- for consumables (HP, energy, etc.)
}

local Items: { [string]: ItemDef } = {
    Medkit = {
        id = "Medkit",
        name = "Medkit",
        category = "Consumable",
        width = 1, height = 2,
        stackable = true, stackMax = 10,
        description = "Restores health. Amount scales with Medicine skill.",
        useEffect = "Heal", valueAmount = 30,
    },
    Biocell = {
        id = "Biocell",
        name = "Power Cell",
        category = "Consumable",
        width = 1, height = 1,
        stackable = true, stackMax = 20,
        description = "Compact bio-electric battery. Restores 100 energy to your biomods.",
        useEffect = "RestoreEnergy", valueAmount = 100,
    },
    Lockpick = {
        id = "Lockpick",
        name = "Lockpick",
        category = "Tool",
        width = 1, height = 1,
        stackable = true, stackMax = 30,
        description = "Used to open locked doors and containers.",
    },
    Multitool = {
        id = "Multitool",
        name = "Multitool",
        category = "Tool",
        width = 1, height = 1,
        stackable = true, stackMax = 30,
        description = "Used to disable security systems and hack panels.",
    },
    AugCanister = {
        id = "AugCanister",
        name = "Biomod Chip",
        category = "Aug",
        width = 1, height = 1,
        stackable = true, stackMax = 10,
        description = "Install one biomod at an AutoMedic.",
    },
    AugUpgradeCanister = {
        id = "AugUpgradeCanister",
        name = "Biomod Upgrade",
        category = "Aug",
        width = 1, height = 1,
        stackable = true, stackMax = 10,
        description = "Upgrades an existing biomod by one level.",
    },
    Ammo10mm = {
        id = "Ammo10mm",
        name = "10mm Rounds",
        category = "Ammo",
        width = 1, height = 1,
        stackable = true, stackMax = 99,
        description = "10mm caliber pistol ammunition.",
    },
    Ammo762 = {
        id = "Ammo762",
        name = "7.62mm Rounds",
        category = "Ammo",
        width = 1, height = 1,
        stackable = true, stackMax = 99,
        description = "Rifle ammunition.",
    },
    AmmoTranq = {
        id = "AmmoTranq",
        name = "Tranquilizer Darts",
        category = "Ammo",
        width = 1, height = 1,
        stackable = true, stackMax = 30,
        description = "Non-lethal sedative crossbow darts.",
    },
    AmmoRocket = {
        id = "AmmoRocket",
        name = "Rocket",
        category = "Ammo",
        width = 1, height = 2,
        stackable = true, stackMax = 4,
        description = "GEP-gun guided rocket.",
    },
    AmmoPlasma = {
        id = "AmmoPlasma",
        name = "Plasma Cells",
        category = "Ammo",
        width = 1, height = 1,
        stackable = true, stackMax = 60,
        description = "Compressed plasma fuel cells for the Plasma Rifle.",
    },
    AmmoLAM = {
        id = "AmmoLAM",
        name = "LAM",
        category = "Ammo",
        width = 1, height = 1,
        stackable = true, stackMax = 8,
        description = "Lightweight Attack Munition. Throw to detonate.",
    },
    AmmoKnife = {
        id = "AmmoKnife",
        name = "Throwing Knives",
        category = "Ammo",
        width = 1, height = 1,
        stackable = true, stackMax = 12,
        description = "Balanced steel throwing knives.",
    },

    -- Weapon mods (one-shot consumables; install attaches them to a weapon).
    WeaponModAccuracy = { id = "WeaponModAccuracy", name = "Accuracy Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install on a weapon to reduce spread by 40%." },
    WeaponModRange = { id = "WeaponModRange", name = "Range Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to extend effective range by 50%." },
    WeaponModRecoil = { id = "WeaponModRecoil", name = "Recoil Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to reduce automatic-fire spread by 30%." },
    WeaponModReload = { id = "WeaponModReload", name = "Reload Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to cut reload time by 40%." },
    WeaponModClip = { id = "WeaponModClip", name = "Clip Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to double magazine capacity." },
    WeaponModScope = { id = "WeaponModScope", name = "Scope Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 3,
        description = "Install on a rifle for 2x ADS zoom." },
    WeaponModLaser = { id = "WeaponModLaser", name = "Laser Sight", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to reduce spread by 20% and add a visible laser." },
    WeaponModSilencer = { id = "WeaponModSilencer", name = "Silencer", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to suppress muzzle report (halves enemy hearing range)." },
    WeaponModDamage = { id = "WeaponModDamage", name = "Damage Mod", category = "WeaponMod",
        width = 1, height = 1, stackable = true, stackMax = 5,
        description = "Install to increase base damage by 25%." },
    KeyHelixVial = {
        id = "KeyHelixVial",
        name = "Helix Vial",
        category = "Key",
        width = 1, height = 1,
        stackable = false, stackMax = 1,
        description = "Sealed Helix-Custodial sample case. Contents officially classified as a 'workplace stress mediator'. Recover all five.",
    },
    DataCube = {
        id = "DataCube",
        name = "Data Cube",
        category = "Key",
        width = 1, height = 1,
        stackable = false, stackMax = 1,
        description = "An infolinked data cube containing intel.",
    },
}

return Items
