--!strict
-- Weapon definitions. Damage scales with the player's relevant skill rank
-- (see Skills.lua) and any installed mods (see WeaponMods.lua).
-- Damage scales with the player's relevant skill rank (see Skills.lua).

export type WeaponDef = {
    id: string,
    name: string,
    skill: string,         -- skill id used to compute damage/accuracy
    slot: string,          -- "Pistol", "Rifle", "Heavy", "Melee", "Demolition"
    damage: number,        -- base damage at Untrained
    range: number,         -- max effective range in studs
    rpm: number,           -- rounds per minute (cooldown = 60/rpm)
    magazine: number,      -- shots per reload, 0 = no reload (melee)
    reloadTime: number,
    spread: number,        -- base radians of cone
    ammoType: string?,     -- nil for melee
    automatic: boolean,
    headshotMult: number,
    silenced: boolean,
    description: string,
}

local Weapons: { [string]: WeaponDef } = {
    Combat10mm = {
        id = "Combat10mm",
        name = "Combat Knife",
        skill = "Melee",
        slot = "Melee",
        damage = 18,
        range = 6,
        rpm = 90,
        magazine = 0,
        reloadTime = 0,
        spread = 0,
        ammoType = nil,
        automatic = false,
        headshotMult = 1.5,
        silenced = true,
        description = "Carbon-blade combat knife. Quiet and reliable.",
    },
    Pistol10mm = {
        id = "Pistol10mm",
        name = "9mm Sidearm",
        skill = "Pistol",
        slot = "Pistol",
        damage = 14,
        range = 120,
        rpm = 220,
        magazine = 9,
        reloadTime = 1.4,
        spread = 0.05,
        ammoType = "10mm",
        automatic = false,
        headshotMult = 2.0,
        silenced = false,
        description = "Compact AEGIS-issue sidearm. Reliable, unremarkable.",
    },
    MiniCrossbow = {
        id = "MiniCrossbow",
        name = "Tranq Crossbow",
        skill = "Pistol",
        slot = "Pistol",
        damage = 22,
        range = 150,
        rpm = 60,
        magazine = 1,
        reloadTime = 1.2,
        spread = 0.005,
        ammoType = "Tranq",
        automatic = false,
        headshotMult = 3.0,
        silenced = true,
        description = "Compressed-air tranquilizer crossbow. Silent. Non-lethal.",
    },
    AssaultRifle = {
        id = "AssaultRifle",
        name = "Assault Rifle",
        skill = "Rifle",
        slot = "Rifle",
        damage = 9,
        range = 300,
        rpm = 600,
        magazine = 30,
        reloadTime = 2.2,
        spread = 0.07,
        ammoType = "762",
        automatic = true,
        headshotMult = 1.8,
        silenced = false,
        description = "Standard service rifle. High rate of fire, low accuracy at range.",
    },
    SniperRifle = {
        id = "SniperRifle",
        name = "Marksman Rifle",
        skill = "Rifle",
        slot = "Rifle",
        damage = 90,
        range = 800,
        rpm = 40,
        magazine = 5,
        reloadTime = 2.8,
        spread = 0.001,
        ammoType = "762",
        automatic = false,
        headshotMult = 3.0,
        silenced = false,
        description = "Bolt-action precision rifle. Built for distance.",
    },
    GepGun = {
        id = "GepGun",
        name = "Thermite Launcher",
        skill = "Heavy",
        slot = "Heavy",
        damage = 180,
        range = 400,
        rpm = 15,
        magazine = 1,
        reloadTime = 3.5,
        spread = 0.02,
        ammoType = "Rocket",
        automatic = false,
        headshotMult = 1.0,
        silenced = false,
        description = "Shoulder-fired thermite charge launcher. Anti-armor / anti-construct.",
    },
    RiotProd = {
        id = "RiotProd",
        name = "Stun Baton",
        skill = "Melee",
        slot = "Melee",
        damage = 12,
        range = 5,
        rpm = 30,
        magazine = 0,
        reloadTime = 0,
        spread = 0,
        ammoType = nil,
        automatic = false,
        headshotMult = 1.0,
        silenced = true,
        description = "Non-lethal capacitor baton. Drains target energy on hit.",
    },
    StealthPistol = {
        id = "StealthPistol",
        name = "Whisper Sidearm",
        skill = "Pistol",
        slot = "Pistol",
        damage = 10,
        range = 100,
        rpm = 200,
        magazine = 9,
        reloadTime = 1.5,
        spread = 0.06,
        ammoType = "10mm",
        automatic = false,
        headshotMult = 2.0,
        silenced = true,
        description = "Integrally suppressed sidearm. Lower damage but inaudible at range.",
    },
    PlasmaRifle = {
        id = "PlasmaRifle",
        name = "Plasma Rifle",
        skill = "Rifle",
        slot = "Rifle",
        damage = 22,
        range = 220,
        rpm = 180,
        magazine = 24,
        reloadTime = 2.4,
        spread = 0.04,
        ammoType = "Plasma",
        automatic = true,
        headshotMult = 1.5,
        silenced = false,
        description = "Energy rifle. Plasma bolt; high damage, slow projectile.",
    },
    LAM = {
        id = "LAM",
        name = "Sticky Charge",
        skill = "Heavy",
        slot = "Demolition",
        damage = 200,
        range = 35,
        rpm = 30,
        magazine = 1,
        reloadTime = 0.5,
        spread = 0.05,
        ammoType = "LAM",
        automatic = false,
        headshotMult = 1.0,
        silenced = false,
        description = "Throwable adhesive explosive. Detonates on impact; area damage.",
    },
    ThrowingKnife = {
        id = "ThrowingKnife",
        name = "Throwing Blade",
        skill = "Melee",
        slot = "Melee",
        damage = 25,
        range = 60,
        rpm = 60,
        magazine = 1,
        reloadTime = 0.4,
        spread = 0.005,
        ammoType = "Knife",
        automatic = false,
        headshotMult = 2.5,
        silenced = true,
        description = "Silent ranged melee. Each throw consumes one blade.",
    },
}

return Weapons
